# Generated by Django 5.0.6 on 2024-05-27 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catProd_nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_nom', models.CharField(max_length=50)),
                ('prod_marca', models.CharField(max_length=25)),
                ('prod_prec', models.IntegerField()),
                ('catProd_nom', models.CharField(max_length=100)),
                ('inv_cantTotal', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('rol_id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('rol_description', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_nom', models.CharField(max_length=50)),
                ('prod_marca', models.CharField(default='Generica', max_length=25)),
                ('prod_prec', models.IntegerField(default=1)),
                ('prod_cant', models.IntegerField(default=1)),
                ('catProd_nom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.categoriaproducto')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=15)),
                ('emp_lastname', models.CharField(max_length=20)),
                ('emp_password', models.CharField(default='admin', max_length=20)),
                ('emp_mail', models.EmailField(max_length=254)),
                ('emp_fono', models.IntegerField()),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cli_id', models.AutoField(primary_key=True, serialize=False)),
                ('cli_name', models.CharField(max_length=15)),
                ('cli_lastname', models.CharField(max_length=20)),
                ('cli_password', models.CharField(default='admin', max_length=20)),
                ('cli_mail', models.EmailField(max_length=254)),
                ('cli_fono', models.IntegerField()),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.rol')),
            ],
        ),
    ]
