# Generated by Django 5.0.6 on 2024-05-27 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='catProd_nom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.categoriaproducto'),
        ),
    ]
