# Generated by Django 5.0.6 on 2024-05-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_inventario_catprod_nom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='id',
        ),
        migrations.AddField(
            model_name='inventario',
            name='prod_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
