# Generated by Django 5.0.6 on 2024-06-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_inventario_id_inventario_prod_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cli_rut',
            field=models.CharField(default='1234', max_length=12),
        ),
        migrations.AddField(
            model_name='empleado',
            name='emp_rut',
            field=models.CharField(default='1234', max_length=12),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cli_password',
            field=models.CharField(default='1234', max_length=20),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='emp_password',
            field=models.CharField(default='1234', max_length=20),
        ),
    ]
