# Generated by Django 5.0.6 on 2024-06-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_cliente_cli_rut_empleado_emp_rut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cli_password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cli_rut',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='emp_password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='emp_rut',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
