# Generated by Django 5.0.6 on 2024-06-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_cliente_cli_password_alter_cliente_cli_rut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='prod_img',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
