# Generated by Django 5.0.6 on 2024-06-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_producto_prod_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='prod_img',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
