# Generated by Django 5.0.6 on 2024-06-20 19:02

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_inventario_prod_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='prod_img',
            field=models.ImageField(blank=True, null=True, upload_to=myapp.models.path_and_rename),
        ),
    ]
