# Generated by Django 5.0.6 on 2024-06-20 19:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_inventario_prod_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='prod_ingreso',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
