# Generated by Django 5.0.6 on 2024-06-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_producto_prod_ingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='prod_ingreso',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
