# Generated by Django 5.0.6 on 2024-07-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_pedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Solicitado', 'Solicitado'), ('En Proceso', 'En Proceso'), ('Listo para retiro', 'Listo para retiro'), ('Enviado', 'Enviado'), ('Completado', 'Completado'), ('Cancelado', 'Cancelado')], default='Solicitado', max_length=20),
        ),
    ]
