# Generated by Django 5.0.6 on 2024-07-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo',
            field=models.CharField(choices=[('Retiro en Tienda', 'Retiro en Tienda'), ('Contratar Despacho', 'Contratar Despacho')], default='Retiro en Tienda', max_length=20),
        ),
    ]
